# TheHive application config
# Full reference: https://docs.strangebee.com/thehive/installation-and-configuration/

db.janusgraph {
  storage.backend = cql
  storage.hostname = ["cassandra"]
  storage.cql.cluster-name = thehive
  storage.cql.keyspace = thehive
}

storage {
  provider = localfs
  localfs.location = /opt/thp/thehive/files
}

play.http.secret.key = "{{ thehive_secret }}"

cortex {
  servers = [
    {
      name = "homelab-cortex"
      url = "http://cortex:9001"
      auth {
        type = "bearer"
        key = "CHANGE_ME_AFTER_CORTEX_ORG_KEY_GENERATED"
      }
    }
  ]
}
